name: TEST CI


on: [push]

jobs: 
  first-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo " My first test CI "
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "kingdonb"
        pr_draft: true
        # github_token: ${{ secrets.GITHUB_TOKEN }}